# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5330f4a439e894606a59a7f45a4d0bc56f1cd86f2c283ecc7e138ef64a69a972aa09c544a98c161f34414290862c97bfb84f5a0c98671ce3438485242a335800

test:
  secret_key_base: 9248bf90c26b29f883dad119943aac9f060ab21a8e43b58a8062381ad1e5c7b318520edb983325eb896e59e7e62a2cdff4ebef2162f553cdbc78186ea7c48b5a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
